### PR TITLE
Update homework.sh

### PR DESCRIPTION
**Pull request by MaggieOma**
Title: UofT- DSI -Unix Shell - Homework for session 1

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Add codes 
## What did you learn from the changes you have made?
spacing and accuracy is key for desire outcomes with bash.
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
When removing directories, I also tried the wild card * to see if i could pair that rm and simultaneously remove all file and directories. I would like some help with that please.
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
I had troubles with removing some directories. I think i was supposed to go to use cd
## How were these changes tested?
I used "ls"and pwd to verify
## A reference to a related issue in your repository (if applicable)
the left side control panel is a bit confusing
## @mentions of the person or team responsible for reviewing proposed changes (At least 2 people)
- @dtxe @juliagallucci @michaeladrouillard 

## Checklist
- [Y ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by MaggieOma** [comment]
image
Screenshot 2024-04-24 180723

**Comment by danielrazavi** [comment]
Hi there, glad to see you have began so early and soon on your assignment! That being said, you have unfortunately made a pull request to the wrong repo. You shouldn't be making a pull request to uoft-dsi/shell, but rather your own forked shell repo.

Please read the instructions on your assignment [(Submission Information)](https://github.com/UofT-DSI/shell/blob/main/02_assignments/assignment.md#submission-information) more carefully (specifically the [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md))

**Comment by MaggieOma** [comment]
How can delete it please? Or remove directory?

**Comment by danielrazavi** [comment]
I have already removed it, nothing else to be done here :)

**Pull request closed without merging**
